development:
  adapter: postgresql
  encoding: utf8
  database: mock_development
  host: localhost
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: mock_test
  host: localhost
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: mock_production
  host: localhost
  pool: 5
  username: 
  password:
