/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
/* Header for class mockvis */

#ifndef _Included_mockvis
#define _Included_mockvis
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: frame */
/* Inaccessible static: configuration */
/* Inaccessible static: mockimage */
/* Inaccessible static: solcol */
/* Inaccessible static: solN */
/* Inaccessible static: jobnbr */
/*
 * Class:     mockvis
 * Method:    runmock
 * Signature: (I)V
 */
//JNIEXPORT void JNICALL Java_mockvis_runmock
//  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
